-- ====================================================
-- Database schema for AC215 Project FitAI
-- Based on: exercise_catalog.csv, gym_members_exercise_tracking.csv,
--           gym_recommendation.csv
-- ====================================================

-- Drop old tables if they exist (for idempotency in dev)
DROP TABLE IF EXISTS ml_generated_plans CASCADE;
DROP TABLE IF EXISTS exercise_tracking CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS gym_recommendation CASCADE;

-- ====================================================
-- GYM_RECOMMENDATION
-- Source: gym_recommendation.csv
-- ====================================================
CREATE TABLE gym_recommendation (
    id              SERIAL PRIMARY KEY,
    source_id       INT,                     -- from recommendation dataset "ID"
    sex             VARCHAR(10),
    age             INT,
    height_m        NUMERIC(4,2),
    weight_kg       NUMERIC(5,2),
    bmi             NUMERIC(5,2),
    hypertension    VARCHAR(5),
    diabetes        VARCHAR(5),
    level           VARCHAR(50),
    fitness_goal    VARCHAR(100),
    fitness_type    VARCHAR(100),
    exercises_pref  TEXT,
    equipment_pref  TEXT,
    diet_pref       TEXT,
    recommendation  TEXT,
    created_at      TIMESTAMP DEFAULT NOW()
);

-- ====================================================
-- EXERCISES
-- Source: exercise_catalog.csv
-- ====================================================
CREATE TABLE exercises (
    id                  SERIAL PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    short_demo_url      TEXT,
    long_demo_url       TEXT,
    difficulty_level    VARCHAR(50),
    target_muscle_group VARCHAR(100),
    prime_mover         VARCHAR(100),
    secondary_muscle    VARCHAR(100),
    tertiary_muscle     VARCHAR(100),
    primary_equipment   VARCHAR(100),
    primary_items       INT,
    secondary_equipment VARCHAR(100),
    secondary_items     INT,
    posture             VARCHAR(100),
    arm_usage           VARCHAR(50),
    arm_movement        VARCHAR(50),
    grip                VARCHAR(50),
    load_position       VARCHAR(100),
    leg_movement        VARCHAR(50),
    foot_elevation      VARCHAR(100),
    combo_exercises     TEXT,
    movement_pattern1   VARCHAR(100),
    movement_pattern2   VARCHAR(100),
    movement_pattern3   VARCHAR(100),
    plane1              VARCHAR(100),
    plane2              VARCHAR(100),
    plane3              VARCHAR(100),
    body_region         VARCHAR(100),
    force_type          VARCHAR(100),
    mechanics           VARCHAR(100),
    laterality          VARCHAR(50),
    classification      VARCHAR(100)
);

-- ====================================================
-- EXERCISE TRACKING
-- Source: gym_members_exercise_tracking.csv
-- ====================================================
CREATE TABLE exercise_tracking (
    id                      SERIAL PRIMARY KEY,
    age                     INT,
    gender                  VARCHAR(20),
    weight_kg               NUMERIC(5,2),
    height_m                NUMERIC(4,2),
    max_bpm                 INT,
    avg_bpm                 INT,
    resting_bpm             INT,
    session_duration_hours  NUMERIC(4,2),
    calories_burned         NUMERIC(6,2),
    workout_type            VARCHAR(100),
    fat_percentage          NUMERIC(5,2),
    water_intake_liters     NUMERIC(4,2),
    workout_frequency_week  INT,
    experience_level        INT,
    bmi                     NUMERIC(5,2),
    created_at              TIMESTAMP DEFAULT NOW()
);

-- ====================================================
-- ML_GENERATED_PLANS
-- Generated by ML Core (not from raw data)
-- ====================================================
CREATE TABLE ml_generated_plans (
    id              SERIAL PRIMARY KEY,
    plan_json       JSONB,
    citations       JSONB,
    created_at      TIMESTAMP DEFAULT NOW()
);

-- ====================================================
-- Indexes (optional performance helpers)
-- ====================================================
CREATE INDEX idx_exercises_name ON exercises(name);
